# Deployment action from https://github.com/TartanLlama/actions-eleventy/

name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - source  # default branch; needed to make user GH pages work

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies with NPM
        run: npm install
      - name: Bundle assets with Webpack and build site with Eleventy
        run: npm run build
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./_site
            publish_branch: master
