# Deployment action from https://github.com/TartanLlama/actions-eleventy/

name: deploy
on:
  push:
    branches:
      - source  # default branch; needed to make user GH pages work

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Eleventy Build
        uses: TartanLlama/actions-eleventy@master
        with:
            install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./_site
            publish_branch: master
